<a href="https://colab.research.google.com/github/qwertynerd97/ml2020/blob/master/Homework4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Problem 1
implementing a conv2d function that takes in an input_mat and a kernal_mat and returns the convolved matrix, with valid padding

Import all necessary libraries

In [0]:
import numpy as np
import math as math

Build the conv2d function

In [0]:
def conv2d(input_mat, kernel_mat):
  # Handle input exceptions
  if(input_mat.shape[0] != input_mat.shape[1]):
    raise Exception('Invalid format: Input Matrix is not square')
  if(kernel_mat.shape[0] != kernel_mat.shape[1]):
    raise Exception('Invalid format: Kernel Matrix is not square')
  if kernel_mat.shape[0] > input_mat.shape[0]:
    raise Exception('Invalid format: Kernel Matrix is larger than Input Matrix')

  kernel_size = kernel_mat.shape[0]

  # Even kernals have all padding on bottom right
  if kernel_size % 2 == 0:
    top_padding = 0
    bottom_padding = kernel_size - 1
  # Odd kernals have the same padding on all sides
  else:
    top_padding = math.floor(kernel_size / 2)
    bottom_padding = top_padding

  # The output matrix is the size of the input matrix - padding
  in_size = input_mat.shape[0]
  out_size = in_size - (top_padding + bottom_padding)
  output_matrix = np.empty((out_size, out_size))

  # Each entry in the output matrix is the dot product of
  # the kernal and the appropriate range in the input matrix
  for i in range(out_size):
    for j in range(out_size):
      # Get location of input patch to convolve
      left = i
      right = i + kernel_size
      top = j
      bottom = j + kernel_size
      
      # Get patch from input matrix
      # And convolve
      patch = input_mat[left : right, top : bottom]
      output_matrix[i, j] = np.tensordot(patch, kernel_mat)
  
  return output_matrix

Test code against provided testcases

In [4]:
from scipy import signal

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")

[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!

[[4.]]
Correct output!



Exception: ignored

# Problem 2
Implementing a max_pooling algorithm that calculates the max_pool of a 2d matrix input_matrix with a window size of s

In [0]:
def maxpooling2d(input_mat, s):
  # Handle input exceptions
  if(input_mat.shape[0] != input_mat.shape[1]):
    raise Exception('Invalid format: Input Matrix is not square')
  if s < 0 or s > input_mat.shape[0]:
    raise Exception('Invalid format: Window size is invalid')

  # Get number of rows/columns in input matrix
  in_size = input_mat.shape[0]

  # The output matrix is the size of the input matrix / the window
  out_size = math.ceil(in_size / s)
  output_matrix = np.empty((out_size, out_size))

  # Each entry in the output matrix is the maximum of the corresponding window
  for i in range(out_size):
    for j in range(out_size):
      # Get bounds of each window
      left = i * s
      right = left + s
      top = j * s
      bottom = top + s
      
      # Get patch from input matrix
      # And convolve
      patch = input_mat[left : right, top : bottom]
      output_matrix[i, j] = np.max(patch)
  
  return output_matrix

Run Test cases

In [31]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [0, 1, 1, 2, 2, 1]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!


#Problem 3
Since problem 3 involves modifying an existing notebook, I have broken it out into two other notebooks: [Problem3a.ipynb](https://colab.research.google.com/drive/1VOSfj_-P4ze5oh47iq1Hwfx-RYlffeRY) and [Problem3b.inpyb](https://colab.research.google.com/drive/1STNDYFXyGiQN-JXq6JoQCY8oaFa0ZI6H)